name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # secretsの使い方（例）
      - name: setup python
        uses: actions/setup-python@v2
        env:
            API_KEY: ${{ secrets.API_KEY }}
            LINE_SKEY: ${{ secrets.LINE_SKEY }}
            LINE_AKEY: ${{ secrets.LINE_AKEY }}
