name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      env:
        API_KEY: ${{ secrets.API_KEY }}
        LINE_SKEY: ${{ secrets.LINE_SKEY }}
        LINE_AKEY: ${{ secrets.LINE_AKEY }}
